language: python

python:
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes memcached

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install libevent-dev; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pyflakes --use-mirrors; fi

notifications:
  email: false
